config/routes.rb
Rails.application.routes.draw do
  devise_for :super_users
  devise_for :admins
  devise_for :moderators

  namespace :super_users do
    resources :places, only: %i(index show edit update destroy)
    resources :users, only: %i(index show edit update destroy)
    resources :moderators
    resources :admins
    resources :events
    resources :settings

    root to: "places#index"
  end

  namespace :private do
    resources :places, only: :index
    resources :tokens, only: %i(index show)
  end

  namespace :public do
    resources :violations, only: :show
  end

  namespace :admins do
    resources :violations, except: %i(new create) do
      put 'publish' => 'violations#publish', on: :member
      put 'unpublish' => 'violations#unpublish', on: :member
      get 'new_email' => 'violations#new_email', on: :member
      post 'new_email' => 'violations#create_email', on: :member
    end

    resources :administrations

    root to: "violations#index"
  end

  namespace :moderators do
    resources :news
    resources :moderators
    resources :places
    resources :users

    root to: "news#index"
  end

  namespace :api do
    namespace :v1 do
      root to: 'maps#index'

      resources :users, only: %i(index create show update) do
        delete '/' => 'users#destroy', on: :collection
      end

      resources :violations do
        post "photos" => "violations#photos" , on: :member
      end

      resources :search_chats, only: %i(index)
      resources :chats, only: %i(index show create) do
        resources :messages, only: %i(index create update)
      end

      resources :services, only: %i(index)
      resources :search, only: %i(index)

      resources :black_lists, only: %i(index create update) do
        delete ":phone_number" => "black_lists#destroy", on: :collection
        get ":phone_number" => "black_lists#show", on: :collection
      end

      resources :places, only: %i(index create update show) do
        resources :comments, only: %i(index create destroy)


        resources :events, only: %i(index create show update destroy) do
          get "search" => "events#search", on: :collection
        end

      end

      resources :maps, only: %i(index)
      resources :favourite_events, only: %i(index create)
      resources :news, only: %i(index)

      #TODO: Add constrait for type validation on destroy
      resources :friends, only: %i(index create destroy)
      #TODO: Add constrait for type validation on destroy
      resources :friendships, only: %i(index create destroy)
      resources :violations

      resources :settings, only: %i(show update)
      resources :image_uploads, only: %i(create)
      resources :images_uploads, only: %i(create)
    end
  end
end

app/models/violation.rb
class Violation < ActiveRecord::Base
  include AreaManipulationsConcern

  JSON_ATTRS = %i(id title description latitude longitude category photos)

  belongs_to :user

  enum status: %i(under_consideration published)

  validates :title,
    :description,
    :latitude,
    :longitude,
    presence: true

  def self.status_by_value(status)
    statuses.key(status)
  end
end

app/controllers/admins/violations_controller.rb
class Admins::ViolationsController < Admins::ApplicationController
  def publish
    update_resource(requested_resource, 'published', 'publish')
  end

  def unpublish
    update_resource(requested_resource, 'under_consideration', 'unpublish')
  end

  def edit
    gon.push({ latitude: requested_resource.latitude, longitude: requested_resource.longitude })
    render locals: {
      page: Administrate::Page::Form.new(dashboard, requested_resource),
    }
  end

  def update
    if requested_resource.update(params_with_status)
      redirect_to(
        [namespace, requested_resource],
        notice: translate_with_resource("update.success"),
      )
    else
      render :edit, locals: {
        page: Administrate::Page::Form.new(dashboard, requested_resource),
      }
    end
  end

  def new_email
    @id = params[:id]
    @administrations = Administration.all
  end

  def create_email
    params[:administration].pop
    violation = Violation.find(params[:id])
    url = request.original_url.split('/new_email')[0]
    admins_appeal = params[:message]
    administration_emails = Administration.where(id: params[:administration]).pluck(:email)
    ViolationMailer.complain_email(admins_appeal, administration_emails, url, violation).deliver_later
    redirect_to admins_violations_path, notice: t("administrate.success.email_delivered")
  end

  private

  def params_with_status
    resource_params.merge(status: Violation.status_by_value(Integer(resource_params[:status])))
  end

  def update_resource(resource, status, action)
    translation_hash = {
      requested_resource: requested_resource.id, action: t("administrate.actions.#{action}")
    }
    message = if resource.update(status: status)
        t("administrate.actions.publish_violation", translation_hash)
      else
        t("administrate.errors.not_published", translation_hash)
      end

    redirect_to admins_violations_path, notice: message
  end
end

app/controllers/api/v1/violations_controller.rb
class Api::V1::ViolationsController < Api::BaseController
  def index
    @violations = Violation.violations_nearby(current_user, params[:distance])
  end

  def show
    @violation = Violation.find(params[:id])
  end

  def create
    record_respond(Violation.create!(violation_params), :created)
  end

  def destroy
    record_respond(Violation.find(params[:id]).destroy)
  end

  private

  def violation_params
    params.
      require(:violation).permit(:title, :description, :latitude, :longitude, :category, photos: [])
  end
end

app/views/admins/violations/_collection.html.erb
<table class="collection-data" aria-labelledby="page-title">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <th class="cell-label
        cell-label--<%= attr_type.html_class %>
        cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>
        " scope="col">
        <%= link_to(params.merge(
          collection_presenter.order_params_for(attr_name)
        )) do %>
        <%= t(
          "activerecord.attributes.#{resource_name}.#{attr_name}",
          default: attr_name.to_s,
        ).titleize %>

            <% if collection_presenter.ordered_by?(attr_name) %>
              <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                <%= svg_tag(
                  "administrate/sort_arrow.svg",
                  "sort_arrow",
                  width: "13",
                  height: "13"
                ) %>
              </span>
            <% end %>
          <% end %>
        </th>
      <% end %>
      <th colspan="2" scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <tr class="table__row"
          role="link"
          tabindex="0"
          data-url="<%= polymorphic_path([namespace, resource]) -%>"
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <%= render_field attribute %>
          </td>
        <% end %>

        <% if resource.published? -%>
          <td><%= link_to(
            t("administrate.actions.unpublish"),
            unpublish_admins_violation_path(resource),
            method: :put,
            class: "action-unpublish"
          ) %></td>
        <% else -%>
          <td><%= link_to(
            t("administrate.actions.publish"),
            publish_admins_violation_path(resource),
            method: :put,
            class: "action-publish"
          ) %></td>
        <% end -%>

        <td><%= link_to(
          t("administrate.actions.edit"),
          [:edit, namespace, resource],
          class: "action-edit",
        ) %></td>

        <td><%= link_to(
          t("administrate.actions.send_email"),
          [:new_email, namespace, resource],
          class: "action-send-email",
        ) %></td>

        <td><%= link_to(
          t("administrate.actions.destroy"),
          [namespace, resource],
          class: "table__action--destroy",
          method: :delete,
          data: { confirm: t("administrate.actions.confirm") }
        ) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admins/violations/_form.html.erb
<%= javascript_include_tag "https://api-maps.yandex.ru/2.1/?lang=ru_RU", type: "text/javascript" %>

<div id="map" style="width: 800px; height: 400px"></div>

<%= form_for([namespace, page.resource], html: { class: "form" }) do |f| %>
  <% if page.resource.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(page.resource.errors.count, "error") %>
        prohibited this <%= page.resource_name %> from being saved:
      </h2>

      <ul>
        <% page.resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% page.attributes.each do |attribute| -%>
    <div class="field-unit field-unit--<%= attribute.html_class %>">
      <%= render_field attribute, f: f %>
    </div>
  <% end -%>

  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/violations/edit.html.erb
<% content_for(:title) { "#{t("administrate.actions.edit")} #{page.page_title}" } %>

<header class="header">
  <h1 class="header__heading"><%= content_for(:title) %></h1>
  <div class="header__actions">
    <%= link_to(
      "#{t("administrate.actions.show")} #{page.page_title}",
      [namespace, page.resource],
      class: "button",
    ) %>
    <% if page.resource.published? -%>
      <%= link_to(
        t("administrate.actions.unpublish"),
        unpublish_admins_violation_path(page.resource),
        method: :put,
        class: "button action-unpublish"
      ) %>
    <% else -%>
      <%= link_to(
        t("administrate.actions.publish"),
        publish_admins_violation_path(page.resource),
        method: :put,
        class: "button action-publish"
      ) %>
    <% end -%>
  </div>
</header>

<%= render "form", page: page %>

app/views/admins/violations/index.html.erb
<% content_for(:title) do %>
  <%= display_resource_name(page.resource_name) %>
<% end %>

<% content_for(:search) do %>
  <form class="search">
    <span class="search__icon">
      <%= svg_tag "administrate/search.svg", "search", width: 16, height: 16 %>
    </span>
    <input
      type="text"
      name="search"
      class="search__input"
      placeholder="<%= t('administrate.search') %>"
      value="<%= search_term %>"
      aria-label="Search"
    />
    <span class="search__hint">
      Press enter to search
    </span>
  </form>
<% end %>

<header class="header">
  <h1 class="header__heading" id="page-title"><%= content_for(:title) %></h1>
</header>

<%= render "collection", collection_presenter: page, resources: resources %>

<%= paginate resources %>

app/views/admins/violations/new_email.html.erb
<%= form_tag(new_email_admins_violation_path, class: "email_form") do %>
  <%= label_tag "#{t('activerecord.models.violation')} #{@id}" %>
  <%= label_tag t("administrate.labels.email") %>
  <%= text_area_tag :message, 'В данной форме добавьте свой комментарий о проблеме.', rows: 5 %>
  <%= collection_check_boxes(nil, :administration, @administrations, :id, :email) do |b| %>
    <%= b.label(class: "label_check_box") { b.check_box(class: "value_check_box") + b.text + ". " + b.object.title } %>
  <% end %>
  <%= submit_tag t("administrate.actions.send_email") %>
<% end %>